### ISSUE TITLE
Update for VSTS?

### ISSUE THREAD

**Issue by bc3tech** [danielgary/vso-hockeyapp-windows-task#1]
Having a hell of a time using the code here to [create the `vsix` needed for VSTS](https://www.visualstudio.com/integrate/extensions/develop/add-build-task)... I've forked and am working on it but seems like there's a lot more that needs to be thought out.

Any chance of doing the work to make this compatible with VSTS' latest rev?

Thanks

**Comment by danielgary** [comment]
Looks like Hockeyapp natively supports appxbundles now, so no need!
